module.exports = {
  content: [
    './src/**/*.js',
    './src/**/*.jsx',
    './public/index.html',
  ],
  css: [
    './build/static/css/*.css'
  ],
  output: './build/static/css/',
  safelist: {
    // Preserve dynamic classes that PurgeCSS can't detect statically
    standard: [
      /^active$/,
      /^show$/,
      /^fade$/,
      /^collapse$/,
      /^collapsing$/,
      /^modal/,
      /^navbar/,
      /^nav-/,
      /^tab-/,
      /^swiper/,
      /^progress/,
      /^d-/,
      /^justify-/,
      /^align-/,
      /^flex-/,
      /^text-/,
      /^bg-/,
      /^mt-/,
      /^mb-/,
      /^ms-/,
      /^me-/,
      /^pt-/,
      /^pb-/,
      /^ps-/,
      /^pe-/,
      /^px-/,
      /^py-/,
      /^mx-/,
      /^my-/,
      /^p-/,
      /^m-/,
      /^g-/,
      /^col/,
      /^row/,
      /^container/,
      /^w-/,
      /^h-/,
      /^fs-/,
      /^fw-/,
      /^lh-/,
      /^border/,
      /^rounded/,
      /^shadow/,
      /^position-/,
      /^overflow-/,
      /^opacity-/,
      /^visible/,
      /^invisible/,
      /^sr-only/,
      /^visually-hidden/,
    ],
    deep: [
      /data-bs/,
    ],
  },
  defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || [],
};
